import { writeFileSync, mkdirSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { icons as logos } from "@iconify-json/logos";
import { icons as devicon } from "@iconify-json/devicon";
import { icons as simple } from "@iconify-json/simple-icons";
import { icons as mdi } from "@iconify-json/mdi";

const COLLECTIONS = {
  logos,
  devicon,
  "simple-icons": simple,
  mdi
};

const ICONS = [
  // Programming languages
  "logos:java", "logos:rust", "logos:python", "logos:c", "devicon:cplusplus",
  "logos:typescript-icon", "logos:javascript",
  // Frameworks
  "devicon:spring", "logos:nodejs-icon", "logos:express", "logos:fastapi",
  "logos:angular-icon", "logos:react", "logos:electron",
  // AI / LLM
  "mdi:database-search", "mdi:robot-outline", "simple-icons:langchain",
  "mdi:graph-outline", "mdi:connection", "logos:hugging-face",
  "mdi:star-circle-outline", "mdi:vector-polyline", "mdi:vector-combine",
  "mdi:message-text-outline", "mdi:file-search-outline", "mdi:monitor",
  // Databases & caching
  "logos:postgresql", "logos:mysql-icon", "logos:mongodb-icon", "logos:cassandra",
  "logos:neo4j", "logos:elasticsearch", "logos:redis", "logos:neon", "logos:qdrant",
  "mdi:vector-arrange-below", "devicon:hibernate", "logos:drizzle",
  // API & communication
  "mdi:api", "logos:graphql", "logos:grpc", "logos:kafka", "logos:rabbitmq",
  // Security & identity
  "mdi:lock-outline", "mdi:card-account-details-outline", "mdi:account-key-outline",
  "mdi:key-outline", "mdi:shield-account-outline", "simple-icons:owasp",
  "mdi:shield-alert-outline", "mdi:shield-lock-outline",
  // Testing
  "logos:playwright", "logos:puppeteer", "logos:selenium", "logos:cucumber",
  // Tools & version control
  "logos:git-icon", "simple-icons:github", "logos:bitbucket", "logos:postman-icon",
  "logos:jira", "logos:confluence", "mdi:developer-board",
  // Cloud & observability
  "simple-icons:amazonwebservices", "logos:firebase", "simple-icons:render",
  "simple-icons:vercel", "logos:datadog", "mdi:cube-scan",
  // Social / UI
  "simple-icons:linkedin", "simple-icons:whatsapp", "simple-icons:gmail",
  "mdi:school", "mdi:arrow-up-right", "mdi:briefcase-outline", "mdi:map-marker-outline",
  "mdi:code-braces", "mdi:brain", "mdi:chart-line", "mdi:account-group-outline",
  "mdi:file-download-outline", "mdi:download",
  "logos:docker-icon", "logos:kubernetes",
  // Architecture diagram
  "mdi:monitor", "mdi:power", "mdi:server-network",
  "mdi:database-outline", "mdi:source-branch", "mdi:memory", "mdi:shield-check-outline",
  "mdi:identifier", "mdi:database-sync-outline", "logos:postgresql",
  "simple-icons:cursor", "simple-icons:claudecode", "simple-icons:opencode", "simple-icons:trae",
  "simple-icons:cloudflare", "mdi:dns", "mdi:cloud-outline",
  "mdi:heart-pulse", "mdi:shield-search", "mdi:sitemap", "mdi:file-settings-outline",
  "mdi:file-eye-outline", "mdi:swap-horizontal", "mdi:key-remove", "mdi:filter-outline",
  "mdi:chart-bell-curve", "mdi:flash-outline", "mdi:alert-circle-outline", "mdi:sync",
  "mdi:restart", "mdi:source-merge", "mdi:server", "mdi:trending-up", "mdi:network-outline",
  "mdi:rocket-launch-outline", "mdi:file-document-outline", "mdi:certificate-outline", "mdi:clipboard-check-outline",
  "logos:vitess", "logos:prometheus"
];

function resolveIcon(full) {
  const [set, name] = full.split(":");
  const data = COLLECTIONS[set];
  if (!data) return null;

  let icon = data.icons[name];
  if (!icon && data.aliases && data.aliases[name]) {
    let alias = data.aliases[name];
    const visited = new Set();
    let cur = name;
    while (alias && !icon) {
      if (visited.has(cur)) break;
      visited.add(cur);
      cur = alias.parent;
      if (!cur || visited.has(cur)) break;
      icon = data.icons[cur];
      alias = data.aliases[cur];
    }
  }
  if (!icon) return null;

  return {
    body: icon.body,
    width: icon.width || data.width || 24,
    height: icon.height || data.height || 24
  };
}

const out = {};
let missing = 0;
for (const full of ICONS) {
  const r = resolveIcon(full);
  if (!r) {
    console.error("MISSING ICON:", full);
    missing++;
    continue;
  }
  out[full] = r;
}

if (missing > 0) {
  console.error(`\n${missing} icon(s) unresolved. Aborting.`);
  process.exit(1);
}

const dir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "lib");
mkdirSync(dir, { recursive: true });
const file = path.join(dir, "iconsData.js");
const header =
  "// Auto-generated by scripts/build-icons.mjs — do not edit by hand.\n" +
  "// Bundles real brand logos offline (Iconify sets: logos, devicon, simple-icons, mdi).\n";
writeFileSync(file, header + "export const ICONS = " + JSON.stringify(out) + ";\n");
console.log(`\nGenerated src/lib/iconsData.js with ${Object.keys(out).length} icons.`);